# Generated by Django 4.2.7 on 2023-11-13 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_propietario_vehiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.FloatField()),
                ('apartamento', models.IntegerField()),
                ('torre', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartamento', models.IntegerField()),
                ('torre', models.IntegerField()),
                ('nombreR', models.CharField(max_length=100)),
                ('nombreV', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
