# Generated by Django 4.2.7 on 2023-11-14 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_apartamento_visitante_delete_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propietario', models.CharField(max_length=100)),
                ('residente', models.CharField(max_length=100)),
                ('placa', models.CharField(max_length=10)),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.apartamento')),
            ],
        ),
    ]
