# Generated by Django 4.2.7 on 2023-11-14 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_pjuridica_alter_propiedad_placa'),
    ]

    operations = [
        migrations.CreateModel(
            name='PNatural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tIdentificacion', models.CharField(max_length=250)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('identificacion', models.CharField(max_length=100)),
            ],
        ),
    ]
