# Generated by Django 4.2.7 on 2023-11-14 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_pnatural'),
    ]

    operations = [
        migrations.CreateModel(
            name='PQRSD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tIdentificacion', models.CharField(max_length=250)),
                ('identificacion', models.CharField(max_length=100)),
                ('tipoPQRSD', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=250)),
                ('correo', models.CharField(max_length=250)),
            ],
        ),
    ]
