# Generated by Django 4.2.7 on 2023-11-14 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_zonasc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('hora', models.CharField(max_length=250)),
                ('idApartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.zonasc')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.apartamento')),
            ],
        ),
    ]
