# Generated by Django 4.2.7 on 2023-11-14 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='idApartamento',
            field=models.CharField(max_length=10),
        ),
    ]
