# Generated by Django 4.2.7 on 2023-11-14 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_alter_reserva_idapartamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='idApartamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.apartamento'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.zonasc'),
        ),
    ]
