# Generated by Django 4.2.7 on 2023-11-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0012_alter_reserva_idapartamento_alter_reserva_zona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='dia',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='idApartamento',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='zona',
            field=models.CharField(max_length=250),
        ),
    ]
